In [ ]:
import pandas as pd
import numpy as  np

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',100)

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
train = pd.read_csv('/train.csv')
test = pd.read_csv('/test.csv')
oil = pd.read_csv('/oil.csv')
stores = pd.read_csv('/stores.csv')
transactions = pd.read_csv('/transactions.csv')
holidays = pd.read_csv('/holidays_events.csv')

### Data Head - Train DataFrame

Let's display the first few rows of the `train` DataFrame to verify the data has been loaded correctly.

In [ ]:
display(train.head())

   id        date  store_nbr      family  sales  onpromotion
0   0  2013-01-01          1  AUTOMOTIVE    0.0            0
1   1  2013-01-01          1   BABY CARE    0.0            0
2   2  2013-01-01          1      BEAUTY    0.0            0
3   3  2013-01-01          1   BEVERAGES    0.0            0
4   4  2013-01-01          1       BOOKS    0.0            0

In [ ]:
print("Train Shape:", train.shape)
print("Test Shape:", test.shape)
print("Stores Shape:", stores.shape)
print("Transactions Shape:", transactions.shape)
print("Oil Shape:", oil.shape)
print("Holidays Shape:", holidays.shape)

Train Shape: (3000888, 6)
Test Shape: (28512, 5)
Stores Shape: (54, 5)
Transactions Shape: (83488, 3)
Oil Shape: (1218, 2)
Holidays Shape: (350, 6)

In [ ]:
test.head()

        id        date  store_nbr      family  onpromotion
0  3000888  2017-08-16          1  AUTOMOTIVE            0
1  3000889  2017-08-16          1   BABY CARE            0
2  3000890  2017-08-16          1      BEAUTY            2
3  3000891  2017-08-16          1   BEVERAGES           20
4  3000892  2017-08-16          1       BOOKS            0

In [ ]:
stores.head()

   store_nbr           city                           state type  cluster
0          1          Quito                       Pichincha    D       13
1          2          Quito                       Pichincha    D       13
2          3          Quito                       Pichincha    D        8
3          4          Quito                       Pichincha    D        9
4          5  Santo Domingo  Santo Domingo de los Tsachilas    D        4

In [ ]:
oil.head()

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

In [ ]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [ ]:
holidays.head()

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         object
 2   store_nbr    int64
 3   family       object
 4   sales        float64
 5   onpromotion  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 137.4+ MB

In [ ]:
test.info()
stores.info()
transactions.info()
oil.info()
holidays.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28512 entries, 0 to 28511
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           28512 non-null  int64
 1   date         28512 non-null  object
 2   store_nbr    28512 non-null  int64
 3   family       28512 non-null  object
 4   onpromotion  28512 non-null  int64
dtypes: int64(3), object(2)
memory usage: 1.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   store_nbr  54 non-null     int64
 1   city       54 non-null     object
 2   state      54 non-null     object
 3   type       54 non-null     object
 4   cluster    54 non-null     int64
dtypes: int64(2), object(3)
memory usage: 2.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  object
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   object
 1   dcoilwtico  1175 non-null   float64
dtypes: float64(1), object(1)
memory usage: 19.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    object
 1   type         350 non-null    object
 2   locale       350 non-null    object
 3   locale_name  350 non-null    object
 4   description  350 non-null    object
 5   transferred  350 non-null    bool
dtypes: bool(1), object(5)
memory usage: 14.1+ KB

In [ ]:
train.describe()

                 id     store_nbr         sales   onpromotion
count  3.000888e+06  3.000888e+06  3.000888e+06  3.000888e+06
mean   1.500444e+06  2.750000e+01  3.577757e+02  2.602770e+00
std    8.662819e+05  1.558579e+01  1.101998e+03  1.221888e+01
min    0.000000e+00  1.000000e+00  0.000000e+00  0.000000e+00
25%    7.502218e+05  1.400000e+01  0.000000e+00  0.000000e+00
50%    1.500444e+06  2.750000e+01  1.100000e+01  0.000000e+00
75%    2.250665e+06  4.100000e+01  1.958473e+02  0.000000e+00
max    3.000887e+06  5.400000e+01  1.247170e+05  7.410000e+02

In [ ]:
transactions.describe()

          store_nbr  transactions
count  83488.000000  83488.000000
mean      26.939237   1694.602158
std       15.608204    963.286644
min        1.000000      5.000000
25%       13.000000   1046.000000
50%       27.000000   1393.000000
75%       40.000000   2079.000000
max       54.000000   8359.000000

In [ ]:
train.describe(include='object')

              date      family
count      3000888     3000888
unique        1684          33
top     2017-08-15  AUTOMOTIVE
freq          1782       90936

In [ ]:
stores.describe(include='object')

         city      state type
count      54         54   54
unique     22         16    5
top     Quito  Pichincha    D
freq       18         19   18

In [ ]:
holidays.describe(include='object')

              date     type    locale locale_name description
count          350      350       350         350         350
unique         312        6         3          24         103
top     2014-06-25  Holiday  National     Ecuador    Carnaval
freq             4      221       174         174          10

In [ ]:
train.info()

train.isnull().sum()

train.duplicated().sum()

train.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         object
 2   store_nbr    int64
 3   family       object
 4   sales        float64
 5   onpromotion  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 137.4+ MB

                 id     store_nbr         sales   onpromotion
count  3.000888e+06  3.000888e+06  3.000888e+06  3.000888e+06
mean   1.500444e+06  2.750000e+01  3.577757e+02  2.602770e+00
std    8.662819e+05  1.558579e+01  1.101998e+03  1.221888e+01
min    0.000000e+00  1.000000e+00  0.000000e+00  0.000000e+00
25%    7.502218e+05  1.400000e+01  0.000000e+00  0.000000e+00
50%    1.500444e+06  2.750000e+01  1.100000e+01  0.000000e+00
75%    2.250665e+06  4.100000e+01  1.958473e+02  0.000000e+00
max    3.000887e+06  5.400000e+01  1.247170e+05  7.410000e+02

In [ ]:
train['date']=pd.to_datetime(train['date'])

In [ ]:
train.isnull().sum()

id             0
date           0
store_nbr      0
family         0
sales          0
onpromotion    0
dtype: int64

In [ ]:
train.duplicated().sum()

np.int64(0)

In [ ]:
# Create a copy of the original dataset
train_cleaned = train.copy()

# Convert date to datetime format
train_cleaned['date'] = pd.to_datetime(train_cleaned['date'])

# Verify the data type
train_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         datetime64[ns]
 2   store_nbr    int64
 3   family       object
 4   sales        float64
 5   onpromotion  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 137.4+ MB

In [ ]:
train_cleaned.to_csv("train_cleaned.csv", index=False)

Dataset 2: stores.csv
**bold text**

In [ ]:
stores.info()

stores.isnull().sum()

stores.duplicated().sum()

stores.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   store_nbr  54 non-null     int64
 1   city       54 non-null     object
 2   state      54 non-null     object
 3   type       54 non-null     object
 4   cluster    54 non-null     int64
dtypes: int64(2), object(3)
memory usage: 2.2+ KB

        store_nbr   city      state type    cluster
count   54.000000     54         54   54  54.000000
unique        NaN     22         16    5        NaN
top           NaN  Quito  Pichincha    D        NaN
freq          NaN     18         19   18        NaN
mean    27.500000    NaN        NaN  NaN   8.481481
std     15.732133    NaN        NaN  NaN   4.693395
min      1.000000    NaN        NaN  NaN   1.000000
25%     14.250000    NaN        NaN  NaN   4.000000
50%     27.500000    NaN        NaN  NaN   8.500000
75%     40.750000    NaN        NaN  NaN  13.000000
max     54.000000    NaN        NaN  NaN  17.000000

In [ ]:
stores.isnull().sum()

store_nbr    0
city         0
state        0
type         0
cluster      0
dtype: int64

In [ ]:
stores.duplicated().sum()

np.int64(0)

In [ ]:
# Create a copy of the original dataset
stores_cleaned = stores.copy()

# Verify dataset information
stores_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   store_nbr  54 non-null     int64
 1   city       54 non-null     object
 2   state      54 non-null     object
 3   type       54 non-null     object
 4   cluster    54 non-null     int64
dtypes: int64(2), object(3)
memory usage: 2.2+ KB

In [ ]:
stores_cleaned.to_csv("stores_cleaned.csv", index=False)

DATASET 3: Transactions.csv

In [ ]:
transactions.info()

transactions.isnull().sum()

transactions.duplicated().sum()

transactions.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  object
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.9+ MB

          store_nbr  transactions
count  83488.000000  83488.000000
mean      26.939237   1694.602158
std       15.608204    963.286644
min        1.000000      5.000000
25%       13.000000   1046.000000
50%       27.000000   1393.000000
75%       40.000000   2079.000000
max       54.000000   8359.000000

In [ ]:
transactions_cleaned = transactions.copy()

In [ ]:
transactions_cleaned['date'] = pd.to_datetime(transactions_cleaned['date'])

In [ ]:
transactions_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  datetime64[ns]
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 1.9 MB

In [ ]:
transactions.duplicated().sum()

np.int64(0)

In [ ]:
# Create a copy
transactions_cleaned = transactions.copy()

# Convert date to datetime
transactions_cleaned['date'] = pd.to_datetime(transactions_cleaned['date'])

# Verify
transactions_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  datetime64[ns]
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 1.9 MB

In [ ]:
transactions_cleaned.to_csv("transactions_cleaned.csv", index=False)

DATASET 4 Oil.csv

In [ ]:
oil.info()

oil.isnull().sum()

oil.duplicated().sum()

oil.describe()
oil.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   object
 1   dcoilwtico  1175 non-null   float64
dtypes: float64(1), object(1)
memory usage: 19.2+ KB

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

In [ ]:
oil_cleaned =oil.copy()

In [ ]:
oil_cleaned['date'] = pd.to_datetime(oil_cleaned['date'])

In [ ]:
# Check missing values before cleaning
print("Missing values before:")
print(oil_cleaned.isnull().sum())

Missing values before:
date           0
dcoilwtico    43
dtype: int64

In [ ]:
# Fill missing oil prices using interpolation
oil_cleaned['dcoilwtico'] = oil_cleaned['dcoilwtico'].interpolate(method='linear')

In [ ]:
# Check missing values after cleaning
print("\nMissing values after:")
print(oil_cleaned.isnull().sum())

Missing values after:
date          0
dcoilwtico    1
dtype: int64

In [ ]:
# Verify the data types
oil_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   datetime64[ns]
 1   dcoilwtico  1217 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 19.2 KB

In [ ]:
oil_cleaned['dcoilwtico'].fillna(93.14, inplace=True)

In [ ]:
oil_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   datetime64[ns]
 1   dcoilwtico  1218 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 19.2 KB

In [ ]:
oil_cleaned['dcoilwtico'] = (
    oil_cleaned['dcoilwtico']
    .interpolate(method='linear')
    .bfill()
)

In [ ]:
oil_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   datetime64[ns]
 1   dcoilwtico  1218 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 19.2 KB

In [ ]:
oil_cleaned.to_csv("oil_cleaned.csv", index=False)

DATASET 5 HOLIDAYS-EVENTS.*CSV*

In [ ]:
holidays.info()

holidays.isnull().sum()

holidays.duplicated().sum()

holidays.describe()
holidays.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    object
 1   type         350 non-null    object
 2   locale       350 non-null    object
 3   locale_name  350 non-null    object
 4   description  350 non-null    object
 5   transferred  350 non-null    bool
dtypes: bool(1), object(5)
memory usage: 14.1+ KB

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [ ]:
holidays_cleaned = holidays.copy()

In [ ]:
holidays_cleaned['date'] = pd.to_datetime(holidays_cleaned['date'])

In [ ]:
# Check missing values
print ("Missing values before:")
print(holidays_cleaned.isnull().sum())

Missing values before:
date           0
type           0
locale         0
locale_name    0
description    0
transferred    0
dtype: int64

In [ ]:
#check duplicates
print("\nDuplicate Rows:")
print(holidays_cleaned.duplicated().sum())

Duplicate Rows:
0

In [ ]:
holidays_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    datetime64[ns]
 1   type         350 non-null    object
 2   locale       350 non-null    object
 3   locale_name  350 non-null    object
 4   description  350 non-null    object
 5   transferred  350 non-null    bool
dtypes: bool(1), datetime64[ns](1), object(4)
memory usage: 14.1+ KB

DATASET 6 TEST.CSV

In [ ]:
test.info()

test.isnull().sum()

test.duplicated().sum()

test.describe()
test.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28512 entries, 0 to 28511
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           28512 non-null  int64
 1   date         28512 non-null  object
 2   store_nbr    28512 non-null  int64
 3   family       28512 non-null  object
 4   onpromotion  28512 non-null  int64
dtypes: int64(3), object(2)
memory usage: 1.1+ MB

        id        date  store_nbr      family  onpromotion
0  3000888  2017-08-16          1  AUTOMOTIVE            0
1  3000889  2017-08-16          1   BABY CARE            0
2  3000890  2017-08-16          1      BEAUTY            2
3  3000891  2017-08-16          1   BEVERAGES           20
4  3000892  2017-08-16          1       BOOKS            0

In [ ]:
test_cleaned = test.copy()

In [ ]:
test_cleaned['date'] = pd.to_datetime(test_cleaned['date'])

In [ ]:
print("Missing values before:")
print(test_cleaned.isnull().sum())

Missing values before:
id             0
date           0
store_nbr      0
family         0
onpromotion    0
dtype: int64

In [ ]:
print("\nDuplicate Rows:")
print(test_cleaned.duplicated().sum())

Duplicate Rows:
0

In [ ]:
test_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28512 entries, 0 to 28511
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           28512 non-null  int64
 1   date         28512 non-null  datetime64[ns]
 2   store_nbr    28512 non-null  int64
 3   family       28512 non-null  object
 4   onpromotion  28512 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 1.1+ MB

In [ ]:
print(train_cleaned.info())

print(stores_cleaned.info())

print(transactions_cleaned.info())

print(oil_cleaned.info())

print(holidays_cleaned.info())

print(test_cleaned.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         datetime64[ns]
 2   store_nbr    int64
 3   family       object
 4   sales        float64
 5   onpromotion  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 137.4+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   store_nbr  54 non-null     int64
 1   city       54 non-null     object
 2   state      54 non-null     object
 3   type       54 non-null     object
 4   cluster    54 non-null     int64
dtypes: int64(2), object(3)
memory usage: 2.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  datetime64[ns]
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 1.9 MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   datetime64[ns]
 1   dcoilwtico  1218 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 19.2 KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    datetime64[ns]
 1   type         350 non-null    object
 2   locale       350 non-null    object
 3   locale_name  350 non-null    object
 4   description  350 non-null    object
 5   transferred  350 non-null    bool
dtypes: bool(1), datetime64[ns](1), object(4)
memory usage: 14.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28512 entries, 0 to 28511
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           28512 non-null  int64
 1   date         28512 non-null  datetime64[ns]
 2   store_nbr    28512 non-null  int64
 3   family       28512 non-null  object
 4   onpromotion  28512 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 1.1+ MB
None

In [ ]:
holidays_cleaned.to_csv("holidays_cleaned.csv", index=False)

test_cleaned.to_csv("test_cleaned.csv", index=False)